// Markets / Finance posts curated from X (finance/markets accounts Michael follows).
// Full text + links + media, pulled from each tweet. Markets-relevant only. Manual refresh.
window.FINANCEPOSTS = [
  {author:"Kantro (Michael Kantrowitz)",handle:"MichaelKantro",date:"2026-08-08",repost:false,img:[],links:[],
   text:"There are two trends that largely explain why the market's P/E is about 10% lower this year — 1 is the pricing of Fed policy expectations and the 2nd is explained by the double-digit drop in Mag 7 P/Es due to increasing costs of debt. Neither are because “P/Es are too high” IMO.",
   url:"https://x.com/MichaelKantro/status/2086157605018149289"},
  {author:"Kantro (Michael Kantrowitz)",handle:"MichaelKantro",date:"2026-08-07",repost:false,img:[],links:[],
   text:"The economy is hardly “struggling.” Cyclical macro data is the strongest and broadest we've seen since 2021. And earnings are strong. Are we looking at the same economy?",
   url:"https://x.com/MichaelKantro/status/2085826194100875569"},
  {author:"Kantro (Michael Kantrowitz)",handle:"MichaelKantro",date:"2026-08-07",repost:true,img:[],links:[],
   text:"Barchart: JUST IN — More than 72% of S&P 500 stocks are now trading above their 200-day moving average, the strongest market breadth since December 2024.",
   url:"https://x.com/Barchart/status/2085806471732724068"},
  {author:"David Rosenberg",handle:"EconguyRosie",date:"2026-08-07",repost:false,img:[],links:[],
   text:"The macro bulls are doing their best to paint lipstick on this pig of an employment report, with both the payroll and household surveys showing contraction. The mantra is that the data were distorted by the World Cup effect that apparently was the only reason that state and local government payrolls were down -50k and leisure/hospitality off -40k. But even when you account for these and then adjust for the Birth-Death model and double-counting from the surge in multiple-job holders, payrolls sagged -138k. And then we have the huge negative back revisions to consider that took the YoY job trend to a microscopic +0.2%. Wage growth nearly flatlined last month to boot, and the YoY trend has melted to a five-year low. No way the Fed should be tightening next month and the three dissenters need to head back to the drawing board.",
   url:"https://x.com/EconguyRosie/status/2085737597167337519"},
  {author:"David Rosenberg",handle:"EconguyRosie",date:"2026-08-06",repost:false,img:[],links:[],
   text:"Unit labor costs are running at +1.4% on a YoY basis and productivity has accounted for nearly 90% of the growth in nonfarm business output over the year to Q2, and every nattering negative nabob is still harping about inflation. There's a bull market all right. In obtuseness.",
   url:"https://x.com/EconguyRosie/status/2085362969186095568"},
  {author:"Jim Bianco",handle:"biancoresearch",date:"2026-08-07",repost:false,img:[],links:[],
   text:"Right now, the hardest thing for Fed watchers to understand is the FOMC policy decisions are now made by twelve independent voters, not a chairman who tells the other eleven how to vote. This is why the criticism of Warsh for not providing forward guidance or a reaction function misses the point.",
   url:"https://x.com/biancoresearch/status/2085671198348718093"},
  {author:"Jim Bianco",handle:"biancoresearch",date:"2026-08-06",repost:false,img:[],links:[],
   text:"The CEO is Mat Ishiba, majority owner of the Phoenix Suns and has an option to buy the Chicago White Sox in 2030. This is the oldest story in business: when you're distracted by a professional sports team, let alone two professional sports teams, your original business falls apart.",
   url:"https://x.com/biancoresearch/status/2085686790078202223"},
  {author:"Danielle DiMartino Booth",handle:"DiMartinoBooth",date:"2026-08-08",repost:false,img:[],links:[],
   text:"It's the steadiness of the bleed…",
   url:"https://x.com/DiMartinoBooth/status/2086222424635216142"},
  {author:"Danielle DiMartino Booth",handle:"DiMartinoBooth",date:"2026-08-08",repost:true,img:[],links:[],
   text:"Melody Wright: We are getting back to pre-Covid [foreclosure] levels from a very low floor due to the abundance of loss mitigation. It's hard to get exact numbers because of the data limitations in judicial states, for instance. We should get near Q3 2007 levels by the end of the year.",
   url:"https://x.com/m3_melody/status/2086134876688830964"},
  {author:"Danielle DiMartino Booth",handle:"DiMartinoBooth",date:"2026-08-08",repost:false,img:[],links:["https://na2.hubs.ly/H0732860"],
   text:"The Weekly Quill — Will America Keep Truckin'? Log in to read now. #federalreserve #powell #dimartinobooth #economy #freight #trucking",
   url:"https://x.com/DiMartinoBooth/status/2086186655413916104"},
  {author:"Bob Elliott",handle:"BobEUnlimited",date:"2026-08-08",repost:false,img:[],links:[],
   text:"Sentiment can't get any more bullish. Think about that.",
   url:"https://x.com/BobEUnlimited/status/2086078741508186330"},
  {author:"Bob Elliott",handle:"BobEUnlimited",date:"2026-08-08",repost:false,img:[],links:[],
   text:"“When the extraordinary is priced as consensus, that's a problem.” Great to swing by @BloombergTV Surveillance on Thursday to discuss the leverage-fueled AI mania, the Fed, and why gold is set to shine ahead.",
   url:"https://x.com/BobEUnlimited/status/2086041346612113572"},
  {author:"Bob Elliott",handle:"BobEUnlimited",date:"2026-08-07",repost:false,img:[],links:["https://wsj.com/finance/stocks/oil-analysts-stumped-by-the-case-of-the-missing-barrels-e4c364e6"],
   text:"The consensus view is that oil prices haven't risen as much as feared b/c of significant demand destruction. More likely it's much larger inventory drawdowns than estimated. Nice shout out to Nonconsensus from @Spencerjakab.",
   url:"https://x.com/BobEUnlimited/status/2085761712746017053"},
  {author:"Amanda Agati (PNC)",handle:"AmandaAgatiPNC",date:"2026-08-06",repost:false,img:["https://pbs.twimg.com/amplify_video_thumb/2085416832077299712/img/UiLS1neaIB2RlOGT.jpg"],links:[],
   text:"My advice for this market? Stay invested. Stay the course. Do nothing. The brilliantly boring approach. 4 straight quarters of earnings beats suggest this rally is being supported by fundamentals, not speculation. Volatility may pick up as we head toward the midterms, but that's not the same thing as deteriorating fundamentals. Thanks so much to @tomkeene & @ptsweeney for having me on @BloombergRadio Surveillance!",
   url:"https://x.com/AmandaAgatiPNC/status/2085416954249293866"},
  {author:"Amanda Agati (PNC)",handle:"AmandaAgatiPNC",date:"2026-08-04",repost:false,img:[],links:[],
   text:"It's bananas, B-A-N-A-N-A-S! Safe to say Q2 EPS has been a very bright spot for markets so far. Still a ways to go yet, but breadth is expanding, a healthy signal, with 9 out of 11 $SPY sectors posting positive y-o-y growth. Corporate America remains in good shape.",
   url:"https://x.com/AmandaAgatiPNC"},
  {author:"Cameron Dawson",handle:"CameronDawson",date:"2026-08-03",repost:false,img:[],links:["https://youtu.be/MqRyEV4-1-E?t=348"],
   text:"7/28 on Bloomberg Surveillance.",
   url:"https://x.com/CameronDawson/status/2084404941926416660"},
  {author:"Cameron Dawson",handle:"CameronDawson",date:"2026-08-01",repost:false,img:[],links:["https://t.co/i8MPHg6CIK"],
   text:"Friday on CNBC Closing Bell Overtime — charting resilience, earnings, and valuations.",
   url:"https://x.com/CameronDawson/status/2083547590444892177"},
  {author:"Cameron Dawson",handle:"CameronDawson",date:"2026-07-24",repost:true,img:["https://pbs.twimg.com/amplify_video_thumb/2080660693976584192/img/wb_EKztYfXSu3byo.jpg"],links:[],
   text:"RiskReversal Media: The latest episode of the RiskReversal Podcast with @CameronDawson (CIO, NewEdge Wealth) on the AI trade — “Just because you're early in the adoption curve of something, doesn't mean you're early in the investment curve.”",
   url:"https://x.com/RiskReversal/status/2080680272803012735"},
  {author:"Katie Stockton, CMT",handle:"StocktonKatie",date:"2026-08-05",repost:false,img:[],links:[],
   text:"Joining @CNBCFastMoney today to address $SPX new high, gold, and more — hope you can tune in. #fairleadstrategies",
   url:"https://x.com/StocktonKatie/status/2085046155885343122"},
  {author:"Katie Stockton, CMT",handle:"StocktonKatie",date:"2026-07-29",repost:true,img:["https://pbs.twimg.com/media/HOZvjJrXMAAI2mW.jpg"],links:["https://cnb.cx/44WTSPZ"],
   text:"Squawk Box: “I think there's still risk to the downside for the Nasdaq 100,” says Fairlead's @StocktonKatie, “and it's a bit too early to get excited about the downdraft as a buying opportunity in the AI trade.”",
   url:"https://x.com/SquawkCNBC/status/2082474534607724833"},
  {author:"Katie Stockton, CMT",handle:"StocktonKatie",date:"2026-07-28",repost:false,img:[],links:[],
   text:"A big milestone today! Fairlead and Amplify's newest ETF, $BNAV, begins trading. I'm incredibly proud of our team and grateful to @AmplifyETFs for their partnership in bringing this strategy to investors. We believe #bitcoin deserves a disciplined approach.",
   url:"https://x.com/StocktonKatie"},
  {author:"Luke Gromen",handle:"LukeGromen",date:"2026-08-07",repost:false,img:[],links:[],
   text:"So, is AI starting to cut into jobs, or are these numbers “fake news”? If AI is cutting into jobs (as it must near term to justify the bull case), it means AI is competing with Bessent to borrow money (raising Bessent's cost of capital), while undermining Bessent's tax base.",
   url:"https://x.com/LukeGromen/status/2085752490323038587"},
  {author:"Luke Gromen",handle:"LukeGromen",date:"2026-08-08",repost:true,img:[],links:["https://research.gavekal.com/article/a-shifting-global-currency-landscape/"],
   text:"Louis-Vincent Gave: HK has always been a bridge between China and the West. As the global financial system that has endured since 1971 starts to fracture, HK's role should turn out to be more important than ever. I recently published a piece on this with @RomainMetivet and asked the Gavekal editors to remove the paywall on this one.",
   url:"https://x.com/gave_vincent/status/2085913247245652294"},
  {author:"Peter Boockvar",handle:"pboockvar",date:"2026-08-06",repost:false,img:[],links:[],
   text:"Interesting comments from DoorDash. As we hear that our lives are going to be driven by bot agents: “I just wondered if you can give us any agentic traffic update, if you're seeing any traffic from there?” The CEO responded: “I mean, what I'd say in short is no, the volume is quite low from some of the agentic partners we've been testing with. But it also isn't that surprising… consumers don't really care what you call this thing, whether you call it agentic flows or pre-agentic flows. They honestly just care about getting their burrito or their pair of Nikes.”",
   url:"https://x.com/pboockvar/status/2085327346031001928"},
  {author:"Peter Boockvar",handle:"pboockvar",date:"2026-08-07",repost:true,img:[],links:[],
   text:"Trevor Hall: The Fed, Japan & Gold — Intervention Changes Everything (with @pboockvar and @FrankCappelleri).",
   url:"https://x.com/TrevAHall/status/2085721699689939318"},
  {author:"Thomas Thornton",handle:"TommyThornton",date:"2026-08-07",repost:false,img:[],links:[],
   text:"The latest Hedge Fund Telemetry note is out. Trimmed some $ADBE after a 36% move from last buy and sold $ARM +24% long. Added to two new shorts, both having DeMark Combo 13 sell signals developing.",
   url:"https://x.com/TommyThornton/status/2085776895065420109"},
  {author:"Thomas Thornton",handle:"TommyThornton",date:"2026-08-07",repost:false,img:[],links:[],
   text:"Nice to see $PCT up 7% after conf call. The next 6 months will be more important than the last 6 months as production ramps.",
   url:"https://x.com/TommyThornton/status/2085777306002321594"},
  {author:"Carter Worth",handle:"CarterBWorth",date:"2026-08-03",repost:true,img:[],links:["https://t.co/MIGOOFYmbD"],
   text:"CNBC Fast Money — Final Trades! Here's what @CourtneyDoming, @GuyAdami, @timseymour and @CarterBWorth are trading: $TJX, $TGT, $CAT, $BABA.",
   url:"https://x.com/CNBCFastMoney/status/2084403087897198708"},
  {author:"Carter Worth",handle:"CarterBWorth",date:"2026-08-03",repost:true,img:[],links:["https://cnb.cx/3TQkMXp"],
   text:"CNBC Fast Money: Chart Master @CarterBWorth sets up for Amgen earnings. $AMGN",
   url:"https://x.com/CNBCFastMoney/status/2084399301334049009"},
  {author:"Carter Worth",handle:"CarterBWorth",date:"2026-08-03",repost:true,img:[],links:["https://t.co/MskfCj1jOO"],
   text:"CNBC Fast Money: Software stocks are surging. @GuyAdami, @timseymour, @CourtneyDoming and @CarterBWorth discuss the move.",
   url:"https://x.com/CNBCFastMoney/status/2084389367502532650"},
  {author:"Michael Kramer",handle:"MichaelMOTTCM",date:"2026-08-08",repost:false,img:[],links:[],
   text:"To this point, the rise in 10-yr real yields has not produced a meaningful correction in stock prices. History suggests that if real yields continue to rise, it will be hard to avoid.",
   url:"https://x.com/MichaelMOTTCM"},
  {author:"Liz Thomas",handle:"LizThomasStrat",date:"2026-08-07",repost:false,img:[],links:[],
   text:"Jobs surprisingly *fell* by 23k vs the est for a gain of 80k and the prior two months were revised down by 103k. And yet the unemployment rate continues to fall, now 4.1%.",
   url:"https://x.com/LizThomasStrat/status/2085742148125647053"},
  {author:"Liz Thomas",handle:"LizThomasStrat",date:"2026-08-05",repost:false,img:[],links:[],
   text:"New episode of The Important Part goes live on YouTube at 3pm ET — Shannon Saccocia is on to talk about how to make money while taking the right risks in your portfolio.",
   url:"https://x.com/LizThomasStrat/status/2085077769394790"},
  {author:"Eliant Capital",handle:"eliant_capital",date:"2026-08-07",repost:false,img:[],links:[],
   text:"Peak hawkishness is here.",
   url:"https://x.com/eliant_capital/status/2085707168175571012"},
  {author:"Eliant Capital",handle:"eliant_capital",date:"2026-08-06",repost:true,img:[],links:[],
   text:"Lyn Alden: What's really going to bake your noodle later on is realizing that rate hikes are not nearly as effective at dealing with deficit-driven inflation as they are at dealing with lending-driven inflation.",
   url:"https://x.com/LynAldenContact/status/2085238426723389846"},
  {author:"Eliant Capital",handle:"eliant_capital",date:"2026-08-06",repost:false,img:[],links:[],
   text:"You don't own enough hard assets.",
   url:"https://x.com/eliant_capital/status/2085177539429900307"},
  {author:"Beth Kindig",handle:"Beth_Kindig",date:"2026-08-05",repost:false,img:[],links:[],
   text:"Google's AI tokens processed across its platforms increased from 9.7 trillion in May 2024 to more than 3.2 quadrillion in May 2026, representing nearly 7x YoY growth and increasing demand for AI inference. $GOOG $AVGO $NVDA",
   url:"https://x.com/Beth_Kindig/status/2085111030577832093"},
  {author:"Beth Kindig",handle:"Beth_Kindig",date:"2026-08-06",repost:false,img:[],links:[],
   text:"While Big Tech is approaching $50 billion annual AI run rates, capex is running up to 4X higher, and further AI revenue growth could only reinforce the spending cycle. This week, we look at exactly how far AI capex outpaces AI revenue, and who wins in the spending race. $GOOG $MSFT $META $AMZN",
   url:"https://x.com/Beth_Kindig/status/2085383640628728038"},
  {author:"Beth Kindig",handle:"Beth_Kindig",date:"2026-08-04",repost:false,img:[],links:[],
   text:"AMD ($AMD) is acquiring chip startup Taalas, which develops specialized chips aiming to reduce computing and memory bottlenecks in inference workloads. AMD is expected to integrate Taalas' tech into its roadmap.",
   url:"https://x.com/Beth_Kindig"},
  {author:"Special Situations (Jay)",handle:"SpecialSitsNews",date:"2026-08-07",repost:false,img:[],links:[],
   text:"$TEAM earnings beat (we own): Non-GAAP diluted EPS came in at $1.87, significantly crushing Wall Street's $1.50 expectation. Revenue surged 28% YoY to $1.77 billion, beating the $1.66B consensus. Cloud revenue grew 31% YoY to $1.21 billion, the primary engine for the quarter. Non-GAAP operating margin expanded sharply to 36% (up from 24% last year), with a positive GAAP operating margin of 12%.",
   url:"https://x.com/SpecialSitsNews"},
  {author:"Special Situations (Jay)",handle:"SpecialSitsNews",date:"2026-08-07",repost:false,img:[],links:[],
   text:"Shorted some $DOCS this morning in the educational discord at $37… covered near $32.",
   url:"https://x.com/SpecialSitsNews/status/2085729079517417554"},
  {author:"Special Situations (Jay)",handle:"SpecialSitsNews",date:"2026-08-07",repost:false,img:[],links:[],
   text:"Memory underperforming again. $MU $SKHY $NVDA $DRAM $EWY",
   url:"https://x.com/SpecialSitsNews/status/2085740496656142442"},
  {author:"Ian King",handle:"IanKingBusiness",date:"2026-08-05",repost:false,img:[],links:["https://t.co/S8O7X3b095"],
   text:"The latest CNBC UK Exchange, the @CNBC newsletter to which I contribute, is out today. This week: a lookahead to tomorrow's strategic update from @Diageo_News, a company whose fortunes (and those of its predecessors) I have followed for three decades.",
   url:"https://x.com/IanKingBusiness/status/2084912739718160823"},
  {author:"Brian Sullivan",handle:"SullyCNBC",date:"2026-08-07",repost:false,img:[],links:[],
   text:"I lived north of San Diego as a kid. Just saw a house listed near our old neighborhood — $1.8 million for a 3 bedroom, 2 bath with just over 1,500 sq ft and not near the beach. Easy to understand why young people are so frustrated (or moving).",
   url:"https://x.com/SullyCNBC/status/2085871849368433151"},
  {author:"Andy Constan",handle:"dampedspring",date:"2026-08-08",repost:true,img:[],links:[],
   text:"Helene Meisler's Saturday poll: the next 100 points for the S&P — up or down?",
   url:"https://x.com/Chartfest1/status/2086044816941400116"},
  {author:"Barry Knapp (Ironsides Macro)",handle:"barryknapp",date:"2026-08-03",repost:false,img:[],links:["https://open.substack.com/pub/ironsidesmacro"],
   text:"Monday Morning Briefer Brief: The end of forward guidance is not adding volatility but removing deleterious volatility suppression and restoring normal market function.",
   url:"https://x.com/barryknapp"}
];
window.FINANCEUPDATED = "Curated from X — Aug 8, 2026";
