// Markets / Finance posts curated from X (finance/markets accounts Michael follows).
// Markets-relevant only (off-topic/political posts skipped). Updated manually on request.
window.FINANCEPOSTS = [
  {author:"Kantro (Michael Kantrowitz)",handle:"MichaelKantro",date:"2026-08-08",repost:false,img:[],
   text:"Two trends largely explain why the market's P/E is ~10% lower this year: 1) the pricing of Fed policy expectations, and 2) the double-digit drop in Mag 7 P/Es due to rising costs of debt. Neither is because “P/Es are too high” IMO.",
   url:"https://x.com/MichaelKantro/status/2086157605018149289"},
  {author:"Kantro (Michael Kantrowitz)",handle:"MichaelKantro",date:"2026-08-07",repost:false,img:[],
   text:"The economy is hardly “struggling.” Cyclical macro data is the strongest and broadest we've seen since 2021, and earnings are strong. Are we looking at the same economy?",
   url:"https://x.com/MichaelKantro/status/2085826194100875569"},
  {author:"Kantro (Michael Kantrowitz)",handle:"MichaelKantro",date:"2026-08-07",repost:true,img:[],
   text:"🔁 Barchart: More than 72% of S&P 500 stocks are now trading above their 200-day moving average — the strongest market breadth since December 2024.",
   url:"https://x.com/MichaelKantro"},
  {author:"David Rosenberg",handle:"EconguyRosie",date:"2026-08-07",repost:false,img:[],
   text:"The macro bulls are doing their best to paint lipstick on this pig of an employment report, with both the payroll and household surveys showing contraction. The mantra is that the data were distorted by the World Cup effect…",
   url:"https://x.com/EconguyRosie/status/2085737597167337519"},
  {author:"David Rosenberg",handle:"EconguyRosie",date:"2026-08-06",repost:false,img:[],
   text:"Unit labor costs are running at +1.4% YoY and productivity has accounted for nearly 90% of the growth in nonfarm business output over the year to Q2. And every nattering negative nabob is still harping about inflation. There's a bull market all right. In obtuseness.",
   url:"https://x.com/EconguyRosie/status/2085362969186095568"},
  {author:"Jim Bianco",handle:"biancoresearch",date:"2026-08-07",repost:false,img:[],
   text:"The hardest thing for Fed watchers to understand right now is that FOMC policy decisions are now made by twelve independent voters, not a chairman who tells the other eleven how to vote.",
   url:"https://x.com/biancoresearch/status/2085671198348718093"},
  {author:"Danielle DiMartino Booth",handle:"DiMartinoBooth",date:"2026-08-08",repost:false,img:[],
   text:"It's the steadiness of the bleed…",
   url:"https://x.com/DiMartinoBooth/status/2086222424635216142"},
  {author:"Danielle DiMartino Booth",handle:"DiMartinoBooth",date:"2026-08-08",repost:false,img:[],
   text:"The Weekly Quill — Will America Keep Truckin'? A look at the freight/trucking read-through for the economy.",
   url:"https://x.com/DiMartinoBooth/status/2086186655413916104"},
  {author:"Bob Elliott",handle:"BobEUnlimited",date:"2026-08-08",repost:false,img:[],
   text:"Sentiment can't get any more bullish. Think about that.",
   url:"https://x.com/BobEUnlimited/status/2086078741508186330"},
  {author:"Bob Elliott",handle:"BobEUnlimited",date:"2026-08-08",repost:false,img:[],
   text:"“When the extraordinary is priced as consensus, that's a problem.” Great to swing by @BloombergTV Surveillance to discuss the leverage-fueled AI mania, the Fed, and why gold is set to shine ahead.",
   url:"https://x.com/BobEUnlimited/status/2086041346612113572"},
  {author:"Amanda Agati (PNC)",handle:"AmandaAgatiPNC",date:"2026-08-06",repost:false,img:["https://pbs.twimg.com/amplify_video_thumb/2085416832077299712/img/UiLS1neaIB2RlOGT.jpg"],
   text:"My advice for this market? Stay invested. Stay the course. Do nothing. The brilliantly boring approach. 4 straight quarters of earnings beats suggest this rally is supported by fundamentals, not speculation.",
   url:"https://x.com/AmandaAgatiPNC/status/2085416954249293866"},
  {author:"Amanda Agati (PNC)",handle:"AmandaAgatiPNC",date:"2026-08-04",repost:false,img:[],
   text:"It's bananas! Q2 EPS has been a very bright spot for markets. Breadth is expanding — a healthy signal — with 9 of 11 $SPY sectors posting positive YoY growth. Corporate America remains in good shape.",
   url:"https://x.com/AmandaAgatiPNC"},
  {author:"Cameron Dawson",handle:"CameronDawson",date:"2026-08-01",repost:false,img:[],
   text:"Friday on CNBC Closing Bell Overtime — charting resilience, earnings, and valuations.",
   url:"https://x.com/CameronDawson/status/2083547590444892177"},
  {author:"Cameron Dawson",handle:"CameronDawson",date:"2026-07-24",repost:true,img:["https://pbs.twimg.com/amplify_video_thumb/2080660693976584192/img/wb_EKztYfXSu3byo.jpg"],
   text:"🔁 On the AI trade (RiskReversal Podcast): “Just because you're early in the adoption curve of something, doesn't mean you're early in the investment curve.”",
   url:"https://x.com/RiskReversal/status/2080680272803012735"},
  {author:"Katie Stockton, CMT",handle:"StocktonKatie",date:"2026-08-05",repost:false,img:[],
   text:"Joining @CNBCFastMoney today to address $SPX new high, gold, and more.",
   url:"https://x.com/StocktonKatie/status/2085046155885343122"},
  {author:"Katie Stockton, CMT",handle:"StocktonKatie",date:"2026-07-29",repost:true,img:["https://pbs.twimg.com/media/HOZvjJrXMAAI2mW.jpg"],
   text:"🔁 Squawk Box: “There's still risk to the downside for the Nasdaq 100,” says Fairlead's Katie Stockton, “too early to get excited about the downdraft as a buying opportunity in the AI trade.”",
   url:"https://x.com/SquawkCNBC/status/2082474534607724833"},
  {author:"Luke Gromen",handle:"LukeGromen",date:"2026-08-07",repost:false,img:[],
   text:"So, is AI starting to cut into jobs, or are these numbers “fake news”? If AI is cutting into jobs (as it must to justify the bull case), it means AI is competing with Bessent to borrow money while undermining his tax base.",
   url:"https://x.com/LukeGromen/status/2085752490323038587"},
  {author:"Peter Boockvar",handle:"pboockvar",date:"2026-08-06",repost:false,img:[],
   text:"Interesting comments from DoorDash. As we hear that our lives are going to be driven by bot agents: “Can you give us any agentic traffic update, if you're seeing any traffic from there?” The CEO's response was telling.",
   url:"https://x.com/pboockvar/status/2085327346031001928"},
  {author:"Thomas Thornton",handle:"TommyThornton",date:"2026-08-07",repost:false,img:[],
   text:"The latest Hedge Fund Telemetry note is out. Trimmed some $ADBE after a 36% move, and sold $ARM +24% long. Added to two new shorts, both with DeMark Combo 13 sell signals developing.",
   url:"https://x.com/TommyThornton/status/2085776895065420109"},
  {author:"Thomas Thornton",handle:"TommyThornton",date:"2026-08-07",repost:false,img:[],
   text:"Nice to see $PCT up 7% after conf call. The next 6 months will be more important than the last 6 as production ramps.",
   url:"https://x.com/TommyThornton/status/2085777306002321594"},
  {author:"Carter Worth",handle:"CarterBWorth",date:"2026-08-03",repost:true,img:[],
   text:"🔁 CNBC Fast Money — Final Trades: Carter Worth's picks alongside the desk were $TJX, $TGT, $CAT, and $BABA.",
   url:"https://x.com/CNBCFastMoney/status/2084403087897198708"},
  {author:"Carter Worth",handle:"CarterBWorth",date:"2026-08-03",repost:true,img:[],
   text:"🔁 Chart Master Carter Worth sets up for Amgen earnings. $AMGN",
   url:"https://x.com/CNBCFastMoney/status/2084399301334049009"},
  {author:"Michael Kramer",handle:"MichaelMOTTCM",date:"2026-08-08",repost:false,img:[],
   text:"To this point, the rise in 10-yr real yields has not produced a meaningful correction in stock prices. History suggests that if real yields continue to rise, it will be hard to avoid.",
   url:"https://x.com/MichaelMOTTCM"},
  {author:"Liz Thomas",handle:"LizThomasStrat",date:"2026-08-07",repost:false,img:[],
   text:"Jobs surprisingly *fell* by 23k vs the est for a gain of 80k, and the prior two months were revised down by 103k. And yet the unemployment rate continues to fall, now 4.1%.",
   url:"https://x.com/LizThomasStrat/status/2085742148125647053"},
  {author:"Eliant Capital",handle:"eliant_capital",date:"2026-08-06",repost:false,img:[],
   text:"The last time gold broke its correlation with real yields was in late '23, and it kicked off a major bull run. It's starting to break that relationship again…",
   url:"https://x.com/eliant_capital/status/2085177539429900307"},
  {author:"Eliant Capital",handle:"eliant_capital",date:"2026-08-07",repost:false,img:[],
   text:"Peak hawkishness is here.",
   url:"https://x.com/eliant_capital/status/2085707168175571012"},
  {author:"Beth Kindig",handle:"Beth_Kindig",date:"2026-08-05",repost:false,img:[],
   text:"Google's AI tokens processed increased from 9.7 trillion in May 2024 to more than 3.2 quadrillion in May 2026 — nearly 7x YoY growth, and rising demand for AI inference. $GOOG $AVGO $NVDA",
   url:"https://x.com/Beth_Kindig/status/2085111030577832093"},
  {author:"Beth Kindig",handle:"Beth_Kindig",date:"2026-08-06",repost:false,img:[],
   text:"While Big Tech is approaching $50 billion annual AI run rates, capex is running up to 4X higher — and further AI revenue growth could only reinforce the spending cycle. Who wins the spending race?",
   url:"https://x.com/Beth_Kindig/status/2085383640628728038"},
  {author:"Special Situations (Jay)",handle:"SpecialSitsNews",date:"2026-08-07",repost:false,img:[],
   text:"$TEAM earnings beat (we own): Non-GAAP diluted EPS came in at $1.87, crushing Wall Street's $1.50. Revenue surged 28% YoY to $1.77 billion, beating the $1.66B consensus.",
   url:"https://x.com/SpecialSitsNews/status/2085740496656142442"},
  {author:"Special Situations (Jay)",handle:"SpecialSitsNews",date:"2026-08-07",repost:false,img:[],
   text:"Memory underperforming again. $MU $SKHY $NVDA $DRAM $EWY",
   url:"https://x.com/SpecialSitsNews/status/2085729079517417554"},
  {author:"Ian King",handle:"IanKingBusiness",date:"2026-08-05",repost:false,img:[],
   text:"The latest CNBC UK Exchange (the @CNBC newsletter I contribute to) is out: a lookahead to Diageo's strategic update — a company whose fortunes I've followed for three decades.",
   url:"https://x.com/IanKingBusiness/status/2084912739718160823"},
  {author:"Brian Sullivan",handle:"SullyCNBC",date:"2026-08-07",repost:false,img:[],
   text:"Can't speak for all of the country, but the upper Midwest seems to be doing pretty well. Everything is crowded and while people grouse about the price of everything, they are spending. Flights are sold out.",
   url:"https://x.com/SullyCNBC/status/2085871849368433151"},
  {author:"Andy Constan",handle:"dampedspring",date:"2026-08-08",repost:true,img:[],
   text:"🔁 Helene Meisler's Saturday poll: the next 100 points for the S&P — up or down?",
   url:"https://x.com/Chartfest1/status/2086044816941400116"}
];
window.FINANCEUPDATED = "Curated from X — Aug 8, 2026";
